### ISSUE TITLE
Is this project maintained?

### ISSUE THREAD

**Issue by wdalmut** [googleworkspace/hubot-google-hangouts-chat#22]
Hi,

we are migrating from slack to Google Chat and we have a couple of bots that we want to bring with us from Slack that are based on Hubot.

Is this project maintained and secure?

**Comment by sqrrrl** [comment]
It hasn't been updated in a while, but hopefully will get some attention soon.

Keep in mind his is not an officially supported Google product. We can't make any claims about the security of the library, though you are free to fork and address any issues that are of concern. Pull requests are also welcome.

**Comment by wdalmut** [comment]
hi @sqrrrl thank you for this project, if we have something to propose we will open a PR. thanks again bests
